//! OpenAPI documentation.

use utoipa::OpenApi;

use crate::handlers;

/// OpenAPI documentation.
#[derive(OpenApi)]
#[openapi(
    info(
        title = "EdgeQuake API",
        version = "0.12.11",
        description = "High-performance RAG system with Knowledge Graph",
        license(name = "Apache-2.0"),
        contact(
            name = "EdgeQuake Team"
        )
    ),
    paths(
        handlers::health_check,
        handlers::readiness_check,
        handlers::liveness_check,
        handlers::get_metrics,
        handlers::upload_document,
        handlers::upload_file,
        handlers::upload_files_batch,
        handlers::list_documents,
        handlers::execute_query,
        handlers::stream_query,
        handlers::query::context::retrieve_query_context,
        handlers::query::context::search_query_context,
        handlers::query::context::fetch_query_context,
        handlers::query::context::get_context_artifact,
        handlers::mcp::mcp_openapi,
        handlers::mcp::mcp_openapi_v1,
        handlers::mcp::mcp_registry_server_json,
        handlers::mcp_oauth_protected_resource,
        handlers::get_graph,
        handlers::stream_graph,
        handlers::get_node,
        handlers::search_labels,
        handlers::list_entities,
        handlers::create_entity,
        handlers::get_entity,
        handlers::update_entity,
        handlers::delete_entity,
        handlers::entity_exists,
        handlers::merge_entities,
        handlers::get_entity_neighborhood,
        handlers::list_relationships,
        handlers::create_relationship,
        handlers::get_relationship,
        handlers::update_relationship,
        handlers::delete_relationship,
        handlers::login,
        handlers::refresh_token,
        handlers::logout,
        handlers::get_me,
        handlers::oidc_login,
        handlers::oidc_callback,
        handlers::create_user,
        handlers::list_users,
        handlers::get_user,
        handlers::delete_user,
        handlers::create_api_key,
        handlers::list_api_keys,
        handlers::revoke_api_key,
        handlers::list_models,
        handlers::list_llm_models,
        handlers::list_embedding_models,
        handlers::get_provider,
        handlers::get_model,
        handlers::check_providers_health,
        handlers::chat::completion::chat_completion,
        handlers::chat::streaming::chat_completion_stream,
        handlers::list_conversations,
        handlers::create_conversation,
        handlers::get_conversation,
        handlers::update_conversation,
        handlers::delete_conversation,
        handlers::list_messages,
        handlers::create_message,
        handlers::bulk_delete_conversations,
        handlers::list_folders,
        handlers::create_folder,
        handlers::update_folder,
        handlers::delete_folder,
        handlers::get_pipeline_status,
        handlers::cancel_pipeline,
        handlers::get_queue_metrics,
        handlers::list_tasks,
        handlers::get_task,
        handlers::cancel_task,
        handlers::retry_task,
        handlers::get_cost_summary,
        handlers::get_model_pricing,
        handlers::estimate_cost,
        handlers::create_tenant,
        handlers::list_tenants,
        handlers::get_tenant,
        handlers::update_tenant,
        handlers::delete_tenant,
        handlers::create_workspace,
        handlers::list_workspaces,
        handlers::get_workspace_by_slug,
        handlers::get_workspace,
        handlers::update_workspace,
        handlers::delete_workspace,
        handlers::get_workspace_stats,
        handlers::get_chunk_detail,
        handlers::get_entity_provenance,
        handlers::get_entity_lineage,
        handlers::get_document_lineage,
        handlers::get_document_full_lineage,
        handlers::get_document_metadata,
        handlers::export_document_lineage,
        handlers::get_chunk_lineage,
        handlers::upload_pdf_document,
        handlers::upload_pdf_batch_document,
        handlers::get_pdf_status,
        handlers::list_pdfs,
        handlers::delete_pdf,
        handlers::get_pdf_progress,
        handlers::get_pdf_content,
        handlers::update_tenant_quota,
        handlers::get_server_defaults,
        handlers::update_server_defaults,
        handlers::storage_inspect,
        handlers::storage_repair,
        handlers::entity_reconcile_plan,
        handlers::entity_reconcile_execute,
        handlers::delete_all_documents,
        handlers::get_track_status,
        handlers::get_document,
        handlers::delete_document,
        handlers::scan_directory,
        handlers::search_documents,
        handlers::reprocess_failed,
        handlers::recover_stuck,
        handlers::analyze_deletion_impact,
        handlers::retry_failed_chunks,
        handlers::list_failed_chunks,
        handlers::reanalyze_multimodal,
        handlers::retry_pdf_processing,
        handlers::cancel_pdf_processing,
        handlers::download_pdf,
        handlers::get_pdf_progress_stream,
        handlers::search_nodes,
        handlers::get_popular_labels,
        handlers::get_degrees_batch,
        handlers::get_cost_history,
        handlers::get_budget_status,
        handlers::update_budget,
        handlers::import_conversations,
        handlers::bulk_archive_conversations,
        handlers::bulk_move_conversations,
        handlers::share_conversation,
        handlers::unshare_conversation,
        handlers::get_shared_conversation,
        handlers::update_message,
        handlers::delete_message,
        handlers::get_metrics_history,
        handlers::trigger_metrics_snapshot,
        handlers::rebuild_embeddings,
        handlers::rebuild_knowledge_graph,
        handlers::reprocess_all_documents,
        handlers::injection::crud::put_injection,
        handlers::injection::injection_file::put_injection_file,
        handlers::injection::crud::list_injections,
        handlers::injection::crud::get_injection,
        handlers::injection::crud::delete_injection,
        handlers::injection::crud::update_injection,
        handlers::update_user,
        handlers::get_provider_status,
        handlers::list_available_providers,
        handlers::get_effective_config,
        handlers::ws_pipeline_progress,
        handlers::ws_progress_by_track_id,
        handlers::create_workspace_job,
        handlers::list_workspace_jobs,
        handlers::list_workspace_job_catalog,
        handlers::get_workspace_job,
        handlers::cancel_workspace_job,
        handlers::ollama_version,
        handlers::ollama_tags,
        handlers::ollama_ps,
        handlers::ollama_chat,
        handlers::ollama_generate,
    ),
    components(schemas(
        handlers::HealthResponse,
        handlers::ApiCapabilities,
        handlers::ComponentHealth,
        handlers::BuildInfo,
        handlers::UploadDocumentRequest,
        handlers::UploadDocumentResponse,
        handlers::FileUploadResponse,
        handlers::BatchUploadResponse,
        handlers::BatchFileResult,
        handlers::ListDocumentsResponse,
        handlers::DocumentSummary,
        handlers::QueryRequest,
        handlers::QueryResponse,
        handlers::SourceReference,
        handlers::QueryStats,
        handlers::StreamQueryRequest,
        handlers::context_types::ContextRetrievalRequest,
        handlers::context_types::ContextRetrievalResponse,
        handlers::context_types::ContextSearchRequest,
        handlers::context_types::ContextSearchResponse,
        handlers::context_types::ContextBundle,
        handlers::context_types::ContentGranularity,
        handlers::KnowledgeGraphResponse,
        handlers::GraphNodeResponse,
        handlers::GraphEdgeResponse,
        handlers::GraphQueryParams,
        handlers::GraphStreamQueryParams,
        handlers::GraphStreamEvent,
        handlers::SearchLabelsQuery,
        handlers::SearchLabelsResponse,
        // Entity schemas (Phase 2)
        handlers::CreateEntityRequest,
        handlers::CreateEntityResponse,
        handlers::UpdateEntityRequest,
        handlers::UpdateEntityResponse,
        handlers::DeleteEntityResponse,
        handlers::DeleteEntityQuery,
        handlers::EntityExistsQuery,
        handlers::EntityExistsResponse,
        handlers::MergeEntitiesRequest,
        handlers::MergeEntitiesResponse,
        handlers::MergeDetails,
        handlers::EntityResponse,
        handlers::GetEntityResponse,
        handlers::RelationshipsInfo,
        handlers::RelationshipSummary,
        handlers::EntityStatistics,
        handlers::ChangesSummary,
        handlers::ListEntitiesQuery,
        handlers::ListEntitiesResponse,
        handlers::EntityNeighborhoodQuery,
        handlers::EntityNeighborhoodResponse,
        handlers::NeighborhoodNode,
        handlers::NeighborhoodEdge,
        // Relationship schemas (Phase 2)
        handlers::CreateRelationshipRequest,
        handlers::CreateRelationshipResponse,
        handlers::UpdateRelationshipRequest,
        handlers::UpdateRelationshipResponse,
        handlers::DeleteRelationshipResponse,
        handlers::RelationshipResponse,
        handlers::GetRelationshipResponse,
        handlers::ListRelationshipsQuery,
        handlers::ListRelationshipsResponse,
        handlers::RelationshipEntities,
        handlers::EntitySummary,
        handlers::RelationshipChangesSummary,
        // Authentication schemas (Phase 3)
        handlers::LoginRequest,
        handlers::LoginResponse,
        handlers::UserInfo,
        handlers::RefreshTokenRequest,
        handlers::RefreshTokenResponse,
        handlers::CreateUserRequest,
        handlers::CreateUserResponse,
        handlers::CreateApiKeyRequest,
        handlers::CreateApiKeyResponse,
        handlers::ApiKeySummary,
        handlers::ListApiKeysResponse,
        handlers::RevokeApiKeyResponse,
        handlers::GetMeResponse,
        // Models Configuration schemas (SPEC-032)
        handlers::ModelsListResponse,
        handlers::ProviderResponse,
        handlers::ModelResponse,
        handlers::ModelCapabilitiesResponse,
        handlers::ModelCostResponse,
        handlers::ProviderHealthResponse,
        handlers::LlmModelsResponse,
        handlers::LlmModelItem,
        handlers::EmbeddingModelsResponse,
        handlers::EmbeddingModelItem,
        // Chat schemas (SDK-aligned)
        handlers::ChatCompletionRequest,
        handlers::ChatCompletionResponse,
        // Conversations & Folders schemas (SDK-aligned)
        handlers::ConversationResponse,
        handlers::MessageResponse,
        handlers::FolderResponse,
        handlers::PaginatedConversationsResponse,
        handlers::PaginatedMessagesResponse,
        handlers::PaginationMetaResponse,
        handlers::ConversationWithMessagesResponse,
        handlers::ShareResponse,
        handlers::CreateConversationApiRequest,
        handlers::UpdateConversationApiRequest,
        handlers::CreateMessageApiRequest,
        handlers::UpdateMessageApiRequest,
        handlers::CreateFolderApiRequest,
        handlers::UpdateFolderApiRequest,
        handlers::BulkOperationRequest,
        handlers::BulkOperationResponse,
        handlers::BulkArchiveRequest,
        handlers::BulkMoveRequest,
        handlers::ImportConversationsRequest,
        handlers::ImportConversationsResponse,
        handlers::ImportErrorResponse,
        handlers::ListConversationsParams,
        handlers::ListMessagesParams,
        // Pipeline schemas (SDK-aligned)
        handlers::EnhancedPipelineStatusResponse,
        handlers::PipelineMessageResponse,
        handlers::CancelPipelineResponse,
        handlers::QueueMetricsResponse,
        // Tasks schemas (SDK-aligned)
        handlers::ListTasksQuery,
        handlers::TaskResponse,
        handlers::TaskErrorResponse,
        handlers::TaskListResponse,
        handlers::PaginationInfo,
        handlers::StatisticsInfo,
        // Costs schemas (SDK-aligned)
        handlers::ModelPricingResponse,
        handlers::CostSummaryResponse,
        handlers::EstimateCostRequest,
        handlers::EstimateCostResponse,
        handlers::CostHistoryQuery,
        handlers::OperationCostResponse,
        handlers::AvailablePricingResponse,
        handlers::WorkspaceCostSummaryResponse,
        handlers::OperationBreakdown,
        handlers::BudgetInfo,
        handlers::CostHistoryPoint,
        // Workspaces & Tenants schemas (SDK-aligned)
        handlers::CreateTenantRequest,
        handlers::UpdateTenantRequest,
        handlers::TenantResponse,
        handlers::TenantListResponse,
        handlers::CreateWorkspaceApiRequest,
        handlers::UpdateWorkspaceApiRequest,
        handlers::WorkspaceResponse,
        handlers::WorkspaceListResponse,
        handlers::PaginationParams,
        handlers::WorkspaceStatsResponse,
        handlers::MetricsSnapshotDTO,
        handlers::MetricsHistoryResponse,
        handlers::RebuildEmbeddingsRequest,
        handlers::RebuildEmbeddingsResponse,
        handlers::ReprocessAllRequest,
        handlers::ReprocessAllResponse,
        handlers::RebuildKnowledgeGraphRequest,
        handlers::RebuildKnowledgeGraphResponse,
        // Lineage & Provenance schemas (OODA-28)
        handlers::ChunkDetailResponse,
        handlers::EntityProvenanceResponse,
        handlers::EntityLineageResponse,
        handlers::ChunkLineageResponse,
        handlers::DocumentGraphLineageResponse,
        handlers::ExtractionStatsResponse,
        handlers::LineRangeInfo,
        handlers::ChunkSourceInfo,
        handlers::EntitySourceInfo,
        handlers::EntitySummaryResponse,
        handlers::RelationshipSummaryResponse,
        handlers::RelatedEntityInfo,
        handlers::SourceDocumentInfo,
        handlers::ExtractedEntityInfo,
        handlers::ExtractedRelationshipInfo,
        handlers::ExtractionMetadataInfo,
        handlers::DescriptionVersionResponse,
        handlers::ExportParams,
        handlers::PdfUploadResponse,
        handlers::PdfMetadata,
        handlers::PdfBatchUploadResponse,
        handlers::PdfBatchFileResult,
        // Documents (extended schemas)
        handlers::DeleteAllDocumentsResponse,
        handlers::DocumentDetailResponse,
        handlers::TrackStatusResponse,
        handlers::ScanDirectoryRequest,
        handlers::ScanDirectoryResponse,
        handlers::ReprocessFailedResponse,
        handlers::RecoverStuckResponse,
        handlers::DeletionImpactResponse,
        handlers::RetryChunksResponse,
        handlers::ListFailedChunksResponse,
        handlers::ReanalyzeMultimodalResponse,
        handlers::PdfOperationResponse,
        // PDF progress (SPEC-027 IMP-013)
        handlers::PdfUploadProgress,
        handlers::PhaseProgress,
        handlers::PhaseError,
        handlers::PipelinePhase,
        handlers::PhaseStatus,
        // Streaming SSE event schemas (SPEC-027 IMP-013)
        handlers::QueryStreamEvent,
        handlers::QueryStreamStats,
        handlers::ChatStreamEvent,
        handlers::CreateJobRequest,
        handlers::JobResponse,
        handlers::JobListResponse,
        handlers::JobLinks,
        handlers::JobCollectionLinks,
        handlers::JobCatalogResponse,
        handlers::JobCatalogEntry,
        handlers::JobCatalogLinks,
        handlers::V2MigrationHint,
        // Graph (extended)
        handlers::SearchNodesQuery,
        handlers::SearchNodesResponse,
        handlers::PopularLabelsQuery,
        handlers::PopularLabelsResponse,
        handlers::BatchDegreeRequest,
        handlers::BatchDegreeResponse,
        // Injection
        handlers::PutInjectionRequest,
        handlers::PutInjectionResponse,
        handlers::UpdateInjectionRequest,
        handlers::InjectionDetailResponse,
        handlers::ListInjectionsResponse,
        handlers::InjectionSummary,
        // Settings
        handlers::EffectiveConfigResponse,
        handlers::ConfigAreaResponse,
        handlers::ConfigLevel,
        crate::provider_types::ProviderStatusResponse,
        crate::provider_types::AvailableProvidersResponse,
        // Ollama Emulation (SPEC-027 IMP-011 phase 2)
        handlers::OllamaVersionResponse,
        handlers::OllamaTagsResponse,
        handlers::OllamaPsResponse,
        handlers::OllamaModel,
        handlers::OllamaModelDetails,
        handlers::OllamaRunningModel,
        handlers::OllamaChatRequest,
        handlers::OllamaChatResponse,
        handlers::OllamaMessage,
        handlers::OllamaGenerateRequest,
        handlers::OllamaGenerateResponse,
        crate::error::ErrorResponse,
    )),
    tags(
        (name = "Health", description = "Health check endpoints"),
        (name = "Observability", description = "Metrics and monitoring endpoints (Phase 3)"),
        (name = "Documents", description = "Document ingestion endpoints"),
        (name = "Query", description = "Query execution endpoints"),
        (name = "Graph", description = "Knowledge graph exploration endpoints"),
        (name = "Entities", description = "Entity CRUD operations (Phase 2)"),
        (name = "Relationships", description = "Relationship CRUD operations (Phase 2)"),
        (name = "Authentication", description = "User authentication and session management (Phase 3)"),
        (name = "User Management", description = "User administration endpoints (Phase 3)"),
        (name = "API Keys", description = "API key management endpoints (Phase 3)"),
        (name = "Models", description = "Model configuration and capability discovery (SPEC-032)"),
        (name = "Chat", description = "Chat completion endpoints for conversational RAG queries"),
        (name = "Conversations", description = "Conversation management - list, create, update, delete conversations and messages"),
        (name = "Folders", description = "Folder management for organizing conversations"),
        (name = "Pipeline", description = "Document processing pipeline status and management"),
        (name = "Tasks", description = "Background task tracking and management"),
        (name = "Costs", description = "LLM usage cost tracking and estimation"),
        (name = "Tenants", description = "Multi-tenant organization management"),
        (name = "Workspaces", description = "Workspace management within tenants"),
        (name = "Lineage", description = "Data lineage and provenance tracking"),
        (name = "PDF", description = "PDF document upload and processing"),
        (name = "Ollama Emulation", description = "Ollama-compatible API for OpenWebUI and similar clients"),
        (name = "Settings", description = "Provider status and effective configuration"),
        (name = "Admin", description = "Administrative operations (auth-gated)"),
        (name = "WebSocket", description = "Real-time progress streaming"),
        (name = "Injection", description = "Workspace knowledge injection"),
        (name = "Jobs", description = "Async job resources (v2)"),
    ),
    security(
        ("bearer_auth" = []),
        ("api_key" = [])
    ),
    modifiers(&SecurityAddon)
)]
pub struct ApiDoc;

/// Security addon for OpenAPI documentation.
/// Also adds tenant/workspace header documentation.
struct SecurityAddon;

impl utoipa::Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "bearer_auth",
                utoipa::openapi::security::SecurityScheme::Http(
                    utoipa::openapi::security::HttpBuilder::new()
                        .scheme(utoipa::openapi::security::HttpAuthScheme::Bearer)
                        .bearer_format("JWT")
                        .build(),
                ),
            );
            components.add_security_scheme(
                "api_key",
                utoipa::openapi::security::SecurityScheme::ApiKey(
                    utoipa::openapi::security::ApiKey::Header(
                        utoipa::openapi::security::ApiKeyValue::new("X-API-Key"),
                    ),
                ),
            );
            // SPEC-032: Add X-Tenant-ID header as security scheme for documentation
            components.add_security_scheme(
                "tenant_id",
                utoipa::openapi::security::SecurityScheme::ApiKey(
                    utoipa::openapi::security::ApiKey::Header(
                        utoipa::openapi::security::ApiKeyValue::new("X-Tenant-ID"),
                    ),
                ),
            );
            // SPEC-032: Add X-Workspace-ID header as security scheme for documentation
            components.add_security_scheme(
                "workspace_id",
                utoipa::openapi::security::SecurityScheme::ApiKey(
                    utoipa::openapi::security::ApiKey::Header(
                        utoipa::openapi::security::ApiKeyValue::new("X-Workspace-ID"),
                    ),
                ),
            );
        }

        crate::openapi_enrichment::apply_openapi_enrichment(openapi);
        crate::openapi_security::apply_path_security(openapi);

        // SPEC-032: Add description about context headers in API description
        if let Some(info) = Some(&mut openapi.info) {
            let current_desc = info.description.clone().unwrap_or_default();
            info.description = Some(format!(
                "{}\n\n## Context Headers (SPEC-032)\n\n\
                 Most endpoints require tenant and workspace context via headers:\n\n\
                 - **X-Tenant-ID**: UUID of the tenant (organization). Required for multi-tenant operations.\n\
                 - **X-Workspace-ID**: UUID of the workspace. Required for document/query operations.\n\n\
                 These headers are automatically set by the WebUI when a user selects a tenant/workspace.\n\n\
                 Example:\n\
                 ```\n\
                 X-Tenant-ID: 00000000-0000-0000-0000-000000000001\n\
                 X-Workspace-ID: 00000000-0000-0000-0000-000000000002\n\
                 ```",
                current_desc
            ));
        }
    }
}
