/**
 * Default API object aggregating all domain modules (SPEC-017 UI-DRY-001).
 */

import {
    getCurrentUser,
    login,
    logout,
    refreshToken,
} from "./auth";
import {
    getBudgetStatus,
    getCostHistory,
    getDocumentCost,
    getIngestionCost,
    getWorkspaceCostSummary,
    updateBudget,
} from "./cost";
import {
    deleteAllDocuments,
    deleteDocument,
    getDocument,
    getDocuments,
    listFailedChunks,
    reprocessDocument,
    reprocessFailedDocuments,
    retryFailedChunks,
    scanDocuments,
    searchDocuments,
    uploadDocument,
    uploadFile,
} from "./documents";
import {
    deleteEntity,
    deleteRelationship,
    getEntities,
    getEntity,
    getEntityNeighborhood,
    getGraph,
    getGraphLabels,
    getGraphStats,
    getPopularLabels,
    getRelationship,
    getRelationships,
    graphStream,
    mergeEntities,
    searchLabels,
    searchNodes,
    updateEntity,
    updateRelationship,
} from "./graph";
import { checkHealth } from "./health";
import {
    deleteInjection,
    getInjection,
    listInjections,
    putInjection,
    updateInjection,
} from "./injection";
import {
    exportDocumentLineage,
    getChunkDetail,
    getChunkLineage,
    getDocumentFullLineage,
    getDocumentLineage,
    getDocumentMetadata,
    getEntityProvenance,
} from "./lineage";
import {
    cancelPipeline,
    cancelTask,
    getEnhancedPipelineStatus,
    getMultipleTrackProgress,
    getPipelineStatus,
    getQueueMetrics,
    getTasksList,
    getTaskStatus,
    getTrackProgress,
    getTrackStatus,
    requestPipelineCancellation,
    retryTask,
} from "./pipeline";
import { query, queryStream } from "./query";
import {
    createTenant,
    createWorkspace,
    deleteWorkspace,
    getTenant,
    getTenants,
    getWorkspace,
    getWorkspaces,
    getWorkspaceStats,
} from "./workspaces";

export const edgequakeApi = {
  checkHealth,
  login,
  logout,
  refreshToken,
  getCurrentUser,
  getTenants,
  getTenant,
  createTenant,
  getWorkspaces,
  getWorkspace,
  getWorkspaceStats,
  createWorkspace,
  deleteWorkspace,
  getDocuments,
  getDocument,
  uploadDocument,
  uploadFile,
  deleteDocument,
  deleteAllDocuments,
  reprocessDocument,
  scanDocuments,
  reprocessFailedDocuments,
  retryFailedChunks,
  listFailedChunks,
  searchDocuments,
  query,
  queryStream,
  getGraph,
  getGraphLabels,
  getGraphStats,
  searchLabels,
  searchNodes,
  getPopularLabels,
  graphStream,
  getEntities,
  getEntity,
  updateEntity,
  deleteEntity,
  mergeEntities,
  getEntityNeighborhood,
  getRelationships,
  getRelationship,
  updateRelationship,
  deleteRelationship,
  getPipelineStatus,
  cancelPipeline,
  getTasksList,
  getTaskStatus,
  cancelTask,
  retryTask,
  getTrackStatus,
  getEnhancedPipelineStatus,
  requestPipelineCancellation,
  getQueueMetrics,
  getTrackProgress,
  getMultipleTrackProgress,
  getDocumentLineage,
  getDocumentFullLineage,
  getDocumentMetadata,
  getChunkDetail,
  getEntityProvenance,
  getChunkLineage,
  exportDocumentLineage,
  getWorkspaceCostSummary,
  getDocumentCost,
  getIngestionCost,
  getBudgetStatus,
  updateBudget,
  getCostHistory,
  putInjection,
  listInjections,
  getInjection,
  updateInjection,
  deleteInjection,
};

export default edgequakeApi;

export * from "../conversations";
export * from "../folders";
export * from "../query-keys";

