/**
 * Default API object aggregating all domain modules (SPEC-017 UI-DRY-001).
 */

import {
  cancelPipeline,
  cancelTask,
  getEnhancedPipelineStatus,
  getMultipleTrackProgress,
  getPipelineStatus,
  getQueueMetrics,
  getTaskStatus,
  getTasksList,
  getTrackProgress,
  getTrackStatus,
  requestPipelineCancellation,
  retryTask,
} from "./pipeline";
import {
  deleteDocument,
  deleteAllDocuments,
  getDocument,
  getDocuments,
  listFailedChunks,
  reprocessDocument,
  reprocessFailedDocuments,
  retryFailedChunks,
  scanDocuments,
  uploadDocument,
  uploadFile,
} from "./documents";
import { checkHealth } from "./health";
import {
  login,
  logout,
  refreshToken,
  getCurrentUser,
} from "./auth";
import {
  createTenant,
  createWorkspace,
  deleteWorkspace,
  getTenant,
  getTenants,
  getWorkspace,
  getWorkspaces,
  getWorkspaceStats,
} from "./workspaces";
import { query, queryStream } from "./query";
import {
  deleteEntity,
  deleteRelationship,
  getEntity,
  getEntityNeighborhood,
  getEntities,
  getGraph,
  getGraphLabels,
  getGraphStats,
  getPopularLabels,
  getRelationship,
  getRelationships,
  graphStream,
  mergeEntities,
  searchLabels,
  searchNodes,
  updateEntity,
  updateRelationship,
} from "./graph";
import {
  exportDocumentLineage,
  getChunkDetail,
  getChunkLineage,
  getDocumentFullLineage,
  getDocumentLineage,
  getDocumentMetadata,
  getEntityProvenance,
} from "./lineage";
import {
  getBudgetStatus,
  getCostHistory,
  getDocumentCost,
  getIngestionCost,
  getWorkspaceCostSummary,
  updateBudget,
} from "./cost";
import {
  deleteInjection,
  getInjection,
  listInjections,
  putInjection,
  updateInjection,
} from "./injection";

export const edgequakeApi = {
  checkHealth,
  login,
  logout,
  refreshToken,
  getCurrentUser,
  getTenants,
  getTenant,
  createTenant,
  getWorkspaces,
  getWorkspace,
  getWorkspaceStats,
  createWorkspace,
  deleteWorkspace,
  getDocuments,
  getDocument,
  uploadDocument,
  uploadFile,
  deleteDocument,
  deleteAllDocuments,
  reprocessDocument,
  scanDocuments,
  reprocessFailedDocuments,
  retryFailedChunks,
  listFailedChunks,
  query,
  queryStream,
  getGraph,
  getGraphLabels,
  getGraphStats,
  searchLabels,
  searchNodes,
  getPopularLabels,
  graphStream,
  getEntities,
  getEntity,
  updateEntity,
  deleteEntity,
  mergeEntities,
  getEntityNeighborhood,
  getRelationships,
  getRelationship,
  updateRelationship,
  deleteRelationship,
  getPipelineStatus,
  cancelPipeline,
  getTasksList,
  getTaskStatus,
  cancelTask,
  retryTask,
  getTrackStatus,
  getEnhancedPipelineStatus,
  requestPipelineCancellation,
  getQueueMetrics,
  getTrackProgress,
  getMultipleTrackProgress,
  getDocumentLineage,
  getDocumentFullLineage,
  getDocumentMetadata,
  getChunkDetail,
  getEntityProvenance,
  getChunkLineage,
  exportDocumentLineage,
  getWorkspaceCostSummary,
  getDocumentCost,
  getIngestionCost,
  getBudgetStatus,
  updateBudget,
  getCostHistory,
  putInjection,
  listInjections,
  getInjection,
  updateInjection,
  deleteInjection,
};

export default edgequakeApi;

export * from "../conversations";
export * from "../folders";
export * from "../query-keys";
