#!/usr/bin/env python3
"""Export LightRAG R-strategy chunk start offsets for SPEC-026 parity fixtures.

Usage:
  python3 scripts/spec026_export_lightrag_chunks.py \\
    --fixture edgequake/crates/edgequake-pipeline/tests/fixtures/spec026/plain_en.txt \\
    --chunk-size 15 \\
    --output edgequake/crates/edgequake-pipeline/tests/fixtures/spec026/lightrag_r_chunks.json

Requires LightRAG checkout (sibling repo) with langchain-text-splitters installed.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def default_lightrag_root() -> Path:
    here = Path(__file__).resolve().parent.parent
    sibling = here.parent / "LightRAG"
    if sibling.is_dir():
        return sibling
    return Path("/Users/raphaelmansuy/Github/03-working/LightRAG")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fixture", type=Path, required=True)
    parser.add_argument("--chunk-size", type=int, default=15)
    parser.add_argument("--chunk-overlap", type=int, default=0)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--lightrag-root", type=Path, default=default_lightrag_root())
    args = parser.parse_args()

    text = args.fixture.read_text(encoding="utf-8")
    sys.path.insert(0, str(args.lightrag_root))

    try:
        from lightrag.chunker.recursive_character import chunking_by_recursive_character
        from lightrag.utils import TiktokenTokenizer
    except ImportError as exc:
        print(f"LightRAG import failed: {exc}", file=sys.stderr)
        return 1

    seps = ["\n\n", "\n", "。", "！", "？", "；", "，", " ", ""]
    tok = TiktokenTokenizer(model_name="gpt-4o-mini")
    chunks = chunking_by_recursive_character(
        tok,
        text,
        chunk_token_size=args.chunk_size,
        chunk_overlap_token_size=args.chunk_overlap,
        separators=seps,
    )
    starts = [c.get("_source_span", {}).get("start") for c in chunks]

    payload = {
        "fixture": args.fixture.name,
        "chunk_size_tokens": args.chunk_size,
        "chunk_overlap_tokens": args.chunk_overlap,
        "strategy": "recursive",
        "separators": seps,
        "chunk_start_offsets": starts,
        "note": "Generated by scripts/spec026_export_lightrag_chunks.py",
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(starts)} offsets to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
