//! Build script for edgequake-api — build metadata + OpenAPI path SSOT (SPEC-027 phase 15).

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    emit_build_metadata();
    generate_openapi_paths_inc();
}

fn emit_build_metadata() {
    let build_timestamp = utc_now();
    println!("cargo:rustc-env=EDGEQUAKE_BUILD_TIMESTAMP={build_timestamp}");

    let git_hash = git_short_hash().unwrap_or_else(|| "unknown".to_string());
    println!("cargo:rustc-env=EDGEQUAKE_GIT_HASH={git_hash}");

    let git_branch = git_branch().unwrap_or_else(|| "unknown".to_string());
    println!("cargo:rustc-env=EDGEQUAKE_GIT_BRANCH={git_branch}");

    let build_number = build_timestamp
        .replace(['-', ':'], "")
        .replace('T', ".")
        .replace('Z', "");
    println!("cargo:rustc-env=EDGEQUAKE_BUILD_NUMBER={build_number}");

    println!("cargo:rustc-env=UTOIPA_PIN_VERSION=5.4.0");

    println!("cargo:rerun-if-changed=../../.git/HEAD");
    println!("cargo:rerun-if-changed=../../.git/refs/");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/handlers");
}

/// Scan `src/handlers/**` for `#[utoipa::path]` + `pub async fn` and emit `openapi_paths.inc`.
fn generate_openapi_paths_inc() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("MANIFEST_DIR"));
    let handlers_root = manifest_dir.join("src/handlers");
    let openapi_rs = manifest_dir.join("src/openapi.rs");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let out_file = out_dir.join("openapi_paths.inc");

    let mut entries = Vec::new();
    collect_utoipa_handlers(&handlers_root, &mut entries);

    entries.sort_by(|a, b| a.0.cmp(&b.0));
    entries.dedup_by(|a, b| a.1 == b.1);

    let generated: std::collections::BTreeSet<String> =
        entries.iter().map(|(_, fn_name)| fn_name.clone()).collect();

    let openapi_src = fs::read_to_string(&openapi_rs).expect("read openapi.rs");
    let registered = parse_openapi_registered_handlers(&openapi_src);

    let missing: Vec<_> = generated.difference(&registered).cloned().collect();
    let extra: Vec<_> = registered.difference(&generated).cloned().collect();
    if !missing.is_empty() || !extra.is_empty() {
        panic!(
            "OpenAPI path SSOT drift in openapi.rs paths():\n  missing handlers: {missing:?}\n  extra handlers: {extra:?}\n  generated={} registered={}",
            generated.len(),
            registered.len()
        );
    }

    let mut lines = String::from("// @generated by build.rs\n");
    for (_path, fn_name) in &entries {
        lines.push_str(&format!("handlers::{fn_name},\n"));
    }

    fs::write(&out_file, lines).expect("write openapi_paths.inc");
    write_path_count_assert(&out_dir, generated.len());
    println!("cargo:rerun-if-changed=src/openapi.rs");

    eprintln!(
        "edgequake-api build: OpenAPI SSOT OK — {} handler paths",
        generated.len()
    );
}

fn parse_openapi_registered_handlers(openapi_src: &str) -> std::collections::BTreeSet<String> {
    let Some(start) = openapi_src.find("paths(") else {
        return std::collections::BTreeSet::new();
    };
    let Some(end) = openapi_src[start..].find("components(") else {
        return std::collections::BTreeSet::new();
    };
    let block = &openapi_src[start..start + end];

    let mut names = std::collections::BTreeSet::new();
    for line in block.lines() {
        let trimmed = line.trim();
        if !trimmed.starts_with("handlers::") {
            continue;
        }
        let path = trimmed.trim_end_matches(',');
        let fn_name = path.rsplit("::").next().unwrap_or(path);
        names.insert(fn_name.to_string());
    }
    names
}

fn collect_utoipa_handlers(dir: &Path, out: &mut Vec<(String, String)>) {
    let Ok(read_dir) = fs::read_dir(dir) else {
        return;
    };
    for entry in read_dir.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_utoipa_handlers(&path, out);
        } else if path.extension().is_some_and(|e| e == "rs") {
            if let Ok(src) = fs::read_to_string(&path) {
                out.extend(parse_utoipa_handlers(&src));
            }
        }
    }
}

/// Extract `(openapi_path, fn_name)` pairs from handler source.
fn parse_utoipa_handlers(src: &str) -> Vec<(String, String)> {
    let mut found = Vec::new();
    let mut search = 0;
    while let Some(rel) = src[search..].find("#[utoipa::path") {
        let start = search + rel;
        let chunk = safe_prefix(&src[start..], 4096);
        let path = extract_quoted_after(chunk, "path = \"");
        let fn_name = extract_fn_name(chunk);
        if let (Some(path), Some(fn_name)) = (path, fn_name) {
            found.push((path, fn_name));
        }
        search = start + 1;
    }
    found
}

fn safe_prefix(s: &str, max_bytes: usize) -> &str {
    let mut end = max_bytes.min(s.len());
    while end > 0 && !s.is_char_boundary(end) {
        end -= 1;
    }
    &s[..end]
}

fn extract_quoted_after(haystack: &str, needle: &str) -> Option<String> {
    let start = haystack.find(needle)? + needle.len();
    let rest = &haystack[start..];
    let end = rest.find('"')?;
    Some(rest[..end].to_string())
}

fn extract_fn_name(chunk: &str) -> Option<String> {
    for line in chunk.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("pub async fn ") {
            let name: String = rest
                .chars()
                .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
                .collect();
            if !name.is_empty() {
                return Some(name);
            }
        }
    }
    None
}

fn write_path_count_assert(out_dir: &Path, generated_count: usize) {
    let check = format!(
        r#"// @generated compile-time OpenAPI path count SSOT
pub const OPENAPI_GENERATED_HANDLER_COUNT: usize = {generated_count};
"#
    );
    fs::write(out_dir.join("openapi_path_count.rs"), check).expect("write path count");
}

fn utc_now() -> String {
    let output = Command::new("date")
        .args(["-u", "+%Y-%m-%dT%H:%M:%SZ"])
        .output();
    match output {
        Ok(o) if o.status.success() => String::from_utf8_lossy(&o.stdout).trim().to_string(),
        _ => "unknown".to_string(),
    }
}

fn git_short_hash() -> Option<String> {
    let output = Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()?;
    if output.status.success() {
        Some(String::from_utf8_lossy(&output.stdout).trim().to_string())
    } else {
        None
    }
}

fn git_branch() -> Option<String> {
    let output = Command::new("git")
        .args(["rev-parse", "--abbrev-ref", "HEAD"])
        .output()
        .ok()?;
    if output.status.success() {
        Some(String::from_utf8_lossy(&output.stdout).trim().to_string())
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_finds_path_and_fn() {
        let src = r#"
        #[utoipa::path(get, path = "/health", tag = "Health")]
        pub async fn health_check() {}
        "#;
        let v = parse_utoipa_handlers(src);
        assert_eq!(v, vec![("/health".to_string(), "health_check".to_string())]);
    }
}
