//! API request handlers.

pub mod auth;
pub mod chat;
pub mod conversations;
pub mod costs;
pub mod documents;
pub mod documents_types;
pub mod entities;
pub mod graph;
pub mod health;
pub mod lineage;
pub mod metrics;
pub mod ollama;
pub mod pipeline;
pub mod query;
pub mod relationships;
pub mod tasks;
pub mod websocket;
pub mod workspaces;

pub use auth::*;
pub use chat::*;
pub use conversations::*;
pub use costs::*;
pub use documents::*;
pub use documents_types::*;
pub use entities::*;
pub use graph::*;
pub use health::*;
pub use lineage::*;
pub use metrics::*;
pub use ollama::*;
pub use pipeline::*;
pub use query::*;
pub use relationships::*;
pub use tasks::*;
pub use websocket::*;
pub use workspaces::*;
